apiVersion: v1
kind: Pod
metadata:
  name: 
  namespace: mynamespace
  labels:
    app: simpleapp
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
