apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: my-namespace
  labels:
    app: simpleapp
spec:
  containers:
    - name: hello-world-container
      image: httpd-basic-image:latest
      ports:
        - containerPort: 80
          protocol: TCP
  imagePullSecrets:
   - name: mysecret
